name = "any-mail"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[triggers]
crons = ["*/1 * * * *"]  # 每分钟轮询一次

[[d1_databases]]
binding = "DB"
database_name = "any-mail-db"
database_id = "e29da149-96b3-4f77-a864-9fc26338e3d3"
